import { aiSummary } from '../../data/rcmMockData';
import { Sparkles, ChevronRight, Zap } from 'lucide-react';

export default function AIFinancialSummary() {
  return (
    <div className="rcm-ai-card">
      {/* Header */}
      <div className="rcm-ai-header">
        <div className="rcm-ai-icon-wrap">
          <Sparkles size={20} style={{ color: '#818cf8' }} />
        </div>
        <div>
          <div className="rcm-ai-badge">AI Executive Summary</div>
          <div className="rcm-ai-sub">Generated by PulseAI · Revenue Intelligence Engine</div>
        </div>
      </div>

      {/* Headline */}
      <p className="rcm-ai-headline">{aiSummary.headline}</p>

      <div className="rcm-ai-body">
        {/* Insights */}
        <div className="rcm-ai-section">
          <div className="rcm-ai-section-title">
            <Zap size={14} style={{ color: '#818cf8' }} /> Key Insights
          </div>
          <ul className="rcm-ai-insights">
            {aiSummary.insights.map((ins, i) => (
              <li key={i} className="rcm-ai-insight-item">
                <ChevronRight size={13} style={{ color: '#818cf8', flexShrink: 0, marginTop: 2 }} />
                <span>{ins}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* Actions */}
        <div className="rcm-ai-section rcm-ai-actions-section">
          <div className="rcm-ai-section-title">
            <Zap size={14} style={{ color: '#f59e0b' }} /> Recommended Actions
          </div>
          <div className="rcm-ai-actions">
            {aiSummary.actions.map((action, i) => (
              <div key={i} className="rcm-ai-action-chip">
                <span className="rcm-ai-action-num">{i + 1}</span>
                {action}
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
